USE [master]
GO

/****** Object:  Database [Customers_Detail]    Script Date: 07/07/2020 02:55:52 ******/
CREATE DATABASE [Customers_Detail]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Customers_Detail', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SHREENATHSQL\MSSQL\DATA\Customers_Detail.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Customers_Detail_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SHREENATHSQL\MSSQL\DATA\Customers_Detail_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Customers_Detail].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Customers_Detail] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Customers_Detail] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Customers_Detail] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Customers_Detail] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Customers_Detail] SET ARITHABORT OFF 
GO

ALTER DATABASE [Customers_Detail] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Customers_Detail] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Customers_Detail] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Customers_Detail] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Customers_Detail] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Customers_Detail] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Customers_Detail] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Customers_Detail] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Customers_Detail] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Customers_Detail] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Customers_Detail] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Customers_Detail] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Customers_Detail] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Customers_Detail] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Customers_Detail] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Customers_Detail] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Customers_Detail] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Customers_Detail] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Customers_Detail] SET  MULTI_USER 
GO

ALTER DATABASE [Customers_Detail] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Customers_Detail] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Customers_Detail] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Customers_Detail] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Customers_Detail] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Customers_Detail] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Customers_Detail] SET  READ_WRITE 
GO


